.TH 42sh 1 "2016 May 26" "42sh-0.5" "Manpage of 42sh"

.SH NAME

42sh - EPITA's "42" SHell

.SH SYNOPSIS

42sh [GNU long options] [options] [file]

.SH DESCRIPTION

.B 42sh
is an sh-compatible command language interpreter that executes commands
read from the standard input, from a file, from a here-document or from
argument with
.I -c
. 42sh also incorporates useful features from the Bash shell.

.B 42sh
is intended to be a conformant implementation of the Shell and Utilities
portion of the IEEE  POSIX  specification  (IEEE  Standard  1003.1).
.B 42sh
can be configured to be POSIX-conformant by default.

.SH AUTHORS

Jean Treibert, Project Manager of the Century
<jean.treibert@epita.fr>

Martin Lees, Git Destroyer
<martin.lees@epita.fr>

Lucas Moisan, Parser Master
<lucas.moisan@epita.fr>

Thomas Domingues, Lazy Developer
<thomas.domingues@epita.fr>
